name: bloc_infinity_list
description: "Infinite scrolling ListView with BLoC integration for Flutter applications."
version: 0.1.1
repository: https://github.com/ristocloud-group/app-lib-bloc-infinity-list

environment:
  sdk: ^3.5.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ">=0.5.1 <2.0.0"
  plugin_platform_interface: ^2.1.8
  equatable: ^2.0.8
  flutter_bloc: ">=8.1.6 <10.0.0"
  bloc_concurrency: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <7.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.ristocloudgroup.lib.bloc_infinity_list
        pluginClass: BlocInfinityListPlugin
      ios:
        pluginClass: BlocInfinityListPlugin
      linux:
        pluginClass: BlocInfinityListPlugin
      macos:
        pluginClass: BlocInfinityListPlugin
      windows:
        pluginClass: BlocInfinityListPluginCApi
      web:
        pluginClass: BlocInfinityListWeb
        fileName: bloc_infinity_list_web.dart