name: Flutter CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - ".github/badges/**" # Don't run CI just for a badge update
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle" # Automatically caches gradle dependencies

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true # Enables native caching to speed up the workflow

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test